name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Python 3.8 setup
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: System dependencies install
      run: |
        sudo apt update
        sudo apt install -y \
        build-essential git zip unzip openjdk-17-jdk \
        autoconf libtool pkg-config \
        zlib1g-dev libncurses5-dev libncursesw5-dev \
        libtinfo5 cmake libffi-dev libssl-dev

    - name: Python dependencies fix install
      run: |
        python -m pip install --upgrade pip==23.2.1
        pip install setuptool
        pip install "cython<3.0"
        pip install buildozer==1.4.0
        pip install kivy==2.1.0

    - name: Build APK
      run: |
        buildozer android debug
